version: "3"

services:
  web:
    container_name: withdrawal-service
    restart: always
    build: .
    ports:
       - "8095:8095"
#    links:
#      - mongo
#  mongo:
#    container_name: db_withdrawal
#    image: mongo
#    ports:
#      - "27025:27020"