server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:80/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: az-eureka-server.azurewebsites.net

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-service
        uri: http://localhost:8090/
        predicates:
        - Path=/customer/**
      - id: product-service
        uri: http://localhost:8091/
        predicates:
        - Path=/product/**
      - id: purchase-service
        uri: http://localhost:8092/
        predicates:
        - Path=/purchase/**
      - id: transaction-service
        uri: http://localhost:8093/
        predicates:
        - Path=/transaction/**
      - id: account-service
        uri: http://localhost:8094/
        predicates:
        - Path=/account/**
      - id: withdrawal-service
        uri: http://localhost:8095/
        predicates:
        - Path=/withdrawal/**
      - id: deposit-service
        uri: http://localhost:8096/
        predicates:
        - Path=/deposit/**
      - id: credit-service
        uri: http://localhost:8097/
        predicates:
        - Path=/credit/**
      - id: payment-service
        uri: http://localhost:8098/
        predicates:
        - Path=/payment/**
      
##routers
#zuul:
#  routes:
#    customer:
#      path: /api/customer-service/**
#      service-id: customer-service
#      url: http://localhost:8090/
#    product:
#      path: /api/product-service/**
#      service-id: product-service
#      url: http://localhost:8091/
#    purchase:
#      path: /api/purchase-service/**
#      service-id: purchase-service
#      url: http://localhost:8092/
#    transaction:
#      path: /api/transaction-service/**
#      service-id: transaction-service
#      url: http://localhost:8093/
#    account:
#      path: /api/account-service/**
#      service-id: account-service
#      url: http://localhost:8094/
#    withdrawal:
#      path: /api/withdrawal-service/**
#      service-id: withdrawal-service
#      url: http://localhost:8095/
#    deposit:
#      path: /api/deposit-service/**
#      service-id: deposit-service
#      url: http://localhost:8096/
#    credit:
#      path: /api/credit-service/**
#      service-id: credit-service
#      url: http://localhost:8097/
#    payment:
#      path: /api/payment-service/**
#      service-id: payment-service
#      url: http://localhost:8098/
        
