server:
  port: 8080
  hostname: localhost
#  hostname: 192.168.0.106

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-service
        uri: http://${server.hostname}:8090/
        predicates:
        - Path=/customer/**
      - id: product-service
        uri: http://${server.hostname}:8091/
        predicates:
        - Path=/product/**
      - id: purchase-service
        uri: http://${server.hostname}:8092/
        predicates:
        - Path=/purchase/**
      - id: transaction-service
        uri: http://${server.hostname}:8093/
        predicates:
        - Path=/transaction/**
      - id: account-service
        uri: http://${server.hostname}:8094/
        predicates:
        - Path=/account/**
      - id: withdrawal-service
        uri: http://${server.hostname}:8095/
        predicates:
        - Path=/withdrawal/**
      - id: deposit-service
        uri: http://${server.hostname}:8096/
        predicates:
        - Path=/deposit/**
      - id: credit-service
        uri: http://${server.hostname}:8097/
        predicates:
        - Path=/credit/**
      - id: payment-service
        uri: http://${server.hostname}:8098/
        predicates:
        - Path=/payment/**