server:
  port: 8095
#  port: 80
  hostname: localhost
#  hostname: 192.168.0.106
  
spring:
  application:
    name: withdrawal-service
  data:
    mongodb:
      uri: mongodb://arodriguezcu:WoZiG7Enr4sZXJsPA6J1yAICIAeGAzczurFJNm8k3q0apmZjMRPlAdHKqoA4vCnXvwLT40VxnskXjU6AwznsuA==@arodriguezcu.mongo.cosmos.azure.com:10255/db_withdrawal?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@arodriguezcu@
  kafka:
    bootstrap-servers: ${kafka.server.hostname}:${kafka.server.port}

kafka:
  server:
#    hostname: ${server.hostname}
    hostname: 20.94.153.173
    port: 9092
#    port: 29092
#    port: 80

eureka:
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:80/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
#    hostname: ${server.hostname}
    hostname: az-eureka-server.azurewebsites.net

topic:
  name: withdrawal-topic
  partitions: 1
  replicas: 1
            
msg:
  error:
    registro:
      notfound.all: RETIROS NO IDENTIFICADOS
      notfound: RETIRO NO IDENTIFICADO
      notfound.create: RETIRO NO SE PUDO CREAR
      positive: MONTO DEBE SER POSITIVO
      excedd: MONTO EXCEDE EL SALDO DISPONIBLE
      account.exists: NUMERO DE CUENTA NO EXISTE
      card.exists: NUMERO DE TARJETA NO EXISTE
            
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
    instances:
      withdrawalServiceCircuitBreaker:
        baseConfig: default
