version: "3"

services:
  web:
    container_name: transaction-service
    restart: always
    build: .
    ports:
       - "8093:8093"
#    links:
#      - mongo
#  mongo:
#    container_name: db_transaction
#    image: mongo
#    ports:
#      - "27029:27020"