server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arodriguezcu/Proyecto3-everis.git
          searchPaths: config-data
#          username: ${GITUSER}
#          password: ${GITPASS}
          default-label: main
